using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;

namespace Ticari_Otomasyon_DevExpress
{
    public partial class Kasa : Form
    {
        public Kasa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource2.FillAsync();
        }
        SqlBaglanti bgl = new SqlBaglanti();
        private void Kasa_Load(object sender, EventArgs e)
        {
            SqlCommand giderler = new SqlCommand("select SUM(Elektrik+Su+Dogalgaz+Internet+Maaslar+Ekstra)from Giderler",bgl.baglanti());   
            SqlDataReader dr = giderler.ExecuteReader();
            while (dr.Read())
            {
                labelControl3.Text=dr[0]+""+"TL".ToString();
            }
            bgl.baglanti().Close();
            //////////////////////////TOPLAM GİDERLER/////////////////////////////////////
            SqlCommand giderler2 = new SqlCommand("Select SUM(Elektrik) from Giderler", bgl.baglanti());
            SqlDataReader dr2=giderler2.ExecuteReader();
            while (dr2.Read())
            {
                labelControl7.Text = dr2[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            /////////////////////ELEKTRİK GİDERLERİ///////////////////////////////////////////
            SqlCommand giderler3 = new SqlCommand("Select SUM(Maaslar) from Giderler", bgl.baglanti());
            SqlDataReader dr3 = giderler3.ExecuteReader();
            while (dr3.Read())
            {
                labelControl5.Text = dr3[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            ///////////////////////PERSONEL MAAŞLARI////////////////////////////////////////////////
            SqlCommand giderler4 = new SqlCommand("Select SUM(Su) from Giderler", bgl.baglanti());
            SqlDataReader dr4 = giderler4.ExecuteReader();
            while (dr4.Read())
            {
                labelControl9.Text = dr4[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            //////////////////////SU GİDERLERİ/////////////////////////////////////////////////
            SqlCommand giderler5 = new SqlCommand("Select SUM(Dogalgaz) from Giderler", bgl.baglanti());
            SqlDataReader dr5 = giderler5.ExecuteReader();
            while (dr5.Read())
            {
                labelControl11.Text = dr5[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            /////////////////////DOGALGAZ GİDERLERİ///////////////////////////////////////////
            SqlCommand giderler6 = new SqlCommand("Select SUM(Internet) from Giderler", bgl.baglanti());
            SqlDataReader dr6 = giderler6.ExecuteReader();
            while (dr6.Read())
            {
                labelControl13.Text = dr6[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            ///////////////////////////////INTERNET GİDERLERİ//////////////////////////////////////////////
            SqlCommand giderler7 = new SqlCommand("Select SUM(Tutar) from FaturaUrunDetay", bgl.baglanti());
            SqlDataReader dr7 = giderler7.ExecuteReader();
            while (dr7.Read())
            {
                labelControl2.Text = dr7[0] + "" + "TL".ToString();
            }
            bgl.baglanti().Close();
            /////////////////////////////ÜRÜNLERİN GİDERLERİ///////////////////////////////////////////////
        }
    }
}
